/// <reference path="main.ts" />
let tracker = emakefun.createFiveLineTracker(0x50)
basic.forever(function () {
    serial.writeString('digital values:')
    serial.writeNumber(tracker.digitalValue(0))
    serial.writeString(', ')
    serial.writeNumber(tracker.digitalValue(1))
    serial.writeString(', ')
    serial.writeNumber(tracker.digitalValue(2))
    serial.writeString(', ')
    serial.writeNumber(tracker.digitalValue(3))
    serial.writeString(', ')
    serial.writeNumber(tracker.digitalValue(4))
    serial.writeString(', analog values:')
    serial.writeNumber(tracker.analogValue(0))
    serial.writeString(', ')
    serial.writeNumber(tracker.analogValue(1))
    serial.writeString(', ')
    serial.writeNumber(tracker.analogValue(2))
    serial.writeString(', ')
    serial.writeNumber(tracker.analogValue(3))
    serial.writeString(', ')
    serial.writeNumber(tracker.analogValue(4))
    serial.writeLine('')
    basic.pause(100)
})
