let five_line_tracker = emakefun.CreateFiveLineTracker(80)
basic.forever(function () {
    serial.writeString('digital values:')
    serial.writeNumber(five_line_tracker.DigitalValue(0))
    serial.writeString(', ')
    serial.writeNumber(five_line_tracker.DigitalValue(1))
    serial.writeString(', ')
    serial.writeNumber(five_line_tracker.DigitalValue(2))
    serial.writeString(', ')
    serial.writeNumber(five_line_tracker.DigitalValue(3))
    serial.writeString(', ')
    serial.writeNumber(five_line_tracker.DigitalValue(4))
    serial.writeString(', analog values:')
    serial.writeNumber(five_line_tracker.AnalogValue(0))
    serial.writeString(', ')
    serial.writeNumber(five_line_tracker.AnalogValue(1))
    serial.writeString(', ')
    serial.writeNumber(five_line_tracker.AnalogValue(2))
    serial.writeString(', ')
    serial.writeNumber(five_line_tracker.AnalogValue(3))
    serial.writeString(', ')
    serial.writeNumber(five_line_tracker.AnalogValue(4))
    serial.writeLine('')
    basic.pause(100)
})
